import { useEffect, useState, FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { BriefcaseBusiness, FileSignature, Plus, Search, ShieldCheck, UsersRound } from 'lucide-react';
import { getMe, logout, Me } from './api';
import AshesLoader from './AshesLoader';
import AppointmentLetterComposer from './AppointmentLetterComposer';

type ClientRow={_id:string;name:string;email:string;company?:string;docCount:number};
type TeamRow={_id:string;name:string;email:string;teamTitle?:string;department?:string;availability?:string;salaryAmount?:number;salaryCurrency?:string;salaryFrequency?:string;startedAt?:string;employmentStatus?:string;appointmentLetterTitle?:string};

export default function AdminHome(){
 const navigate=useNavigate();
 const[user,setUser]=useState<Me|null>(null),[clients,setClients]=useState<ClientRow[]>([]),[team,setTeam]=useState<TeamRow[]>([]),[loading,setLoading]=useState(true);
 const[tab,setTab]=useState<'clients'|'team'>('clients'),[showAdd,setShowAdd]=useState(false),[creating,setCreating]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[search,setSearch]=useState('');
 const[selectedTeam,setSelectedTeam]=useState<TeamRow|null>(null);
 const[form,setForm]=useState({name:'',email:'',password:'',role:'client',company:'',source:'other',dealValue:'',teamTitle:'Team Member',department:'Delivery'});
 async function load(){const[c,t]=await Promise.all([fetch('/api/admin/clients').then(r=>r.json()),fetch('/api/admin/team-list').then(r=>r.json())]);setClients(Array.isArray(c)?c:[]);setTeam(Array.isArray(t)?t:[])}
 useEffect(()=>{getMe().then(async u=>{if(!u)return navigate('/login');if(u.role!=='admin')return navigate(u.role==='team'?'/team':'/portal');setUser(u);await load();setLoading(false)})},[navigate]);
 async function onLogout(){await logout();navigate('/login')}
 async function onCreate(e:FormEvent){e.preventDefault();setError('');setSuccess('');setCreating(true);const isTeam=form.role==='team';const url=isTeam?'/api/admin/team-create':'/api/admin/create-user';const body=isTeam?{name:form.name,email:form.email,password:form.password,teamTitle:form.teamTitle,department:form.department}:{name:form.name,email:form.email,password:form.password,role:'client',company:form.company,source:form.source,dealValue:form.dealValue};const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();setCreating(false);if(!res.ok)return setError(data.error||'Could not create account.');setSuccess(`${isTeam?'Team':'Client'} account created for ${data.email}.`);setForm({name:'',email:'',password:'',role:isTeam?'team':'client',company:'',source:'other',dealValue:'',teamTitle:'Team Member',department:'Delivery'});await load()}
 if(loading)return <AshesLoader label="Opening admin portal…"/>;
 const filteredClients=clients.filter(c=>`${c.name} ${c.email} ${c.company||''}`.toLowerCase().includes(search.toLowerCase()));
 const filteredTeam=team.filter(t=>`${t.name} ${t.email} ${t.teamTitle||''} ${t.department||''}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="portal-shell admin-directory-shell">
   <div className="portal-topbar"><div className="portal-brand">ASHES <span>· Admin Portal</span></div><div className="portal-nav-actions"><Link className="pill-btn tiny solid" to="/admin/dashboard">Dashboard</Link><Link className="pill-btn tiny" to="/admin/account">Account</Link><span className="portal-user">{user?.name}</span><button className="pill-btn tiny" onClick={onLogout}>Log out</button></div></div>
   <div className="portal-container">
     <div className="admin-directory-head"><div><div className="portal-eyebrow">PEOPLE & ACCESS</div><h1 className="portal-h1">Clients and team.</h1><p className="portal-sub">Clients belong to your private CRM. Team members are internal staff accounts and never see client, revenue, pipeline or finance data.</p></div><button className="pill-btn solid" onClick={()=>setShowAdd(v=>!v)}><Plus size={14}/>{showAdd?'Close':'Add account'}</button></div>
     <div className="admin-people-stats"><article><BriefcaseBusiness/><div><span>Clients</span><strong>{clients.length}</strong><small>CRM accounts</small></div></article><article><UsersRound/><div><span>Team</span><strong>{team.length}</strong><small>internal members</small></div></article><article><ShieldCheck/><div><span>Privacy</span><strong>Separated</strong><small>team cannot access CRM</small></div></article></div>
     {showAdd&&<div className="portal-card"><div className="admin-role-switch"><button className={form.role==='client'?'active':''} onClick={()=>setForm({...form,role:'client'})} type="button">Client account</button><button className={form.role==='team'?'active':''} onClick={()=>setForm({...form,role:'team'})} type="button">Team member</button></div>{error&&<div className="portal-error">{error}</div>}{success&&<div className="portal-success">{success}</div>}<form onSubmit={onCreate}><div className="portal-grid-2"><div className="portal-field"><label>Full name</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="portal-field"><label>Login email</label><input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="portal-field"><label>Temporary password</label><input required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div>{form.role==='team'?<><div className="portal-field"><label>Role / title</label><input value={form.teamTitle} onChange={e=>setForm({...form,teamTitle:e.target.value})}/></div><div className="portal-field"><label>Department</label><input value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></div></>:<><div className="portal-field"><label>Company</label><input value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/></div><div className="portal-field"><label>Lead source</label><select value={form.source} onChange={e=>setForm({...form,source:e.target.value})}><option value="whatsapp">WhatsApp</option><option value="linkedin">LinkedIn</option><option value="instagram">Instagram</option><option value="fiverr">Fiverr</option><option value="referral">Referral</option><option value="other">Other</option></select></div><div className="portal-field"><label>Estimated deal value (PKR)</label><input type="number" value={form.dealValue} onChange={e=>setForm({...form,dealValue:e.target.value})}/></div></>}</div><button className="pill-btn solid" disabled={creating}>{creating?'Creating…':form.role==='team'?'Create team member':'Create client'}</button></form></div>}
     <div className="admin-directory-tabs"><button className={tab==='clients'?'active':''} onClick={()=>{setTab('clients');setSelectedTeam(null)}}>Clients <span>{clients.length}</span></button><button className={tab==='team'?'active':''} onClick={()=>setTab('team')}>Team <span>{team.length}</span></button></div>
     <div className="portal-card"><div className="admin-directory-search"><Search size={16}/><input placeholder={tab==='clients'?'Search clients…':'Search team…'} value={search} onChange={e=>setSearch(e.target.value)}/></div>{tab==='clients'?<table className="portal-table"><thead><tr><th>Name</th><th>Email</th><th>Company</th><th>Docs</th><th></th></tr></thead><tbody>{filteredClients.map(c=><tr key={c._id}><td>{c.name}</td><td>{c.email}</td><td>{c.company||'—'}</td><td>{c.docCount}</td><td><Link className="pill-btn tiny solid" to={`/admin/client/${c._id}`}>Open CRM</Link></td></tr>)}</tbody></table>:<table className="portal-table"><thead><tr><th>Member</th><th>Email</th><th>Title</th><th>Department</th><th>Status</th><th>HR documents</th></tr></thead><tbody>{filteredTeam.map(t=><tr key={t._id}><td>{t.name}</td><td>{t.email}</td><td>{t.teamTitle||'Team Member'}</td><td>{t.department||'Delivery'}</td><td><span className="portal-badge downloaded">{t.employmentStatus||t.availability||'Active'}</span></td><td><button className="pill-btn tiny appointment-table-btn" onClick={()=>setSelectedTeam(t)}><FileSignature size={13}/>{t.appointmentLetterTitle?'Resend letter':'Send appointment'}</button></td></tr>)}</tbody></table>}</div>
     {selectedTeam&&<AppointmentLetterComposer member={selectedTeam} onClose={()=>setSelectedTeam(null)} onSent={load}/>} 
   </div>
 </div>
}
