import { useEffect, useState, FormEvent, Fragment } from 'react';
import { useNavigate } from 'react-router-dom';
import { getMe, logout, Me } from './api';
import AccountSettings from './AccountSettings';
import AshesLoader from './AshesLoader';

const TYPE_LABELS: Record<string, string> = { welcome:'Welcome Packet', contract:'Service Agreement / Contract', invoice:'Invoice', access_request:'Access / Information Request', monthly_report:'Monthly Progress Report', fulfillment:'Fulfillment & Handover', feedback_request:'Feedback Request', custom_file:'File from ASHES' };
type DocRow={_id:string;title:string;type:string;status:string;createdAt:string;paymentStatus?:'unpaid'|'paid';signedAt?:string;signedByName?:string};
type Profile={name:string;email:string;company?:string;project?:string;googleEmail?:string;phone?:string;age?:number;gender?:string};

export default function Portal(){
 const navigate=useNavigate(); const [user,setUser]=useState<Me|null>(null); const [profile,setProfile]=useState<Profile|null>(null); const [docs,setDocs]=useState<DocRow[]>([]); const [myReview,setMyReview]=useState<{rating:number;comment:string}|null>(null); const [reviewRating,setReviewRating]=useState(0); const [reviewComment,setReviewComment]=useState(''); const [hoverStar,setHoverStar]=useState(0); const [submittingReview,setSubmittingReview]=useState(false); const [reviewSaved,setReviewSaved]=useState(false); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [saved,setSaved]=useState(false); const [signingDoc,setSigningDoc]=useState<string|null>(null); const [signName,setSignName]=useState(''); const [signing,setSigning]=useState(false);
 async function refreshDocs(){setDocs(await fetch('/api/documents').then(r=>r.json()))}
 async function submitSignature(id:string){if(!signName.trim())return;setSigning(true);const r=await fetch(`/api/documents/${id}/sign`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({signedByName:signName.trim()})});setSigning(false);if(r.ok){setSigningDoc(null);setSignName('');refreshDocs()}}
 useEffect(()=>{getMe().then(async u=>{if(!u)return navigate('/login');if(u.role==='admin')return navigate('/admin');if(u.role==='team')return navigate('/team');setUser(u);const[p,d,reviews]=await Promise.all([fetch('/api/client/profile').then(r=>r.json()),fetch('/api/documents').then(r=>r.json()),fetch('/api/reviews').then(r=>r.json())]);setProfile(p);setDocs(d);const mine=Array.isArray(reviews)?reviews.find((r:any)=>r.client===u.id):null;if(mine){setMyReview({rating:mine.rating,comment:mine.comment});setReviewRating(mine.rating);setReviewComment(mine.comment||'')}setLoading(false)})},[navigate]);
 async function submitReview(){if(!reviewRating)return;setSubmittingReview(true);const r=await fetch('/api/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rating:reviewRating,comment:reviewComment,clientName:user?.name,company:profile?.company})});setSubmittingReview(false);if(r.ok){setMyReview({rating:reviewRating,comment:reviewComment});setReviewSaved(true);setTimeout(()=>setReviewSaved(false),3000)}}
 async function saveProfile(e:FormEvent){e.preventDefault();setSaving(true);setSaved(false);const r=await fetch('/api/client/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)});setProfile(await r.json());setSaving(false);setSaved(true);setTimeout(()=>setSaved(false),2500)}
 async function onLogout(){await logout();navigate('/login')}
 if(loading||!profile)return <AshesLoader label="Opening your client workspace…"/>;
 const unpaid=docs.filter(d=>d.type==='invoice'&&d.paymentStatus!=='paid').length; const signed=docs.filter(d=>d.type==='contract'&&d.signedAt).length;
 return <div className="client-pro-shell portal-shell">
  <aside className="client-sidebar"><div className="client-logo"><img src="/ashes-logo-transparent.webp"/><div><strong>ASHES</strong><span>CLIENT SPACE</span></div></div><nav><a className="active" href="#overview">Overview</a><a href="#documents">Documents</a><a href="#profile">Profile</a><a href="#feedback">Feedback</a></nav><div className="client-side-bottom"><small>PROJECT</small><strong>{profile.project||'Active project'}</strong><span>{profile.company||'Private client'}</span><button onClick={onLogout}>Log out</button></div></aside>
  <main className="client-main" id="overview"><header className="client-header"><div><span>CLIENT WORKSPACE</span><h1>Welcome back, {user?.name?.split(' ')[0]}</h1><p>A private place for your project, documents, approvals and account details.</p></div><div className="client-project-status"><i/> Project active</div></header>
   <section className="client-kpis"><article><span>Documents</span><strong>{docs.length}</strong><small>shared with you</small></article><article><span>Contracts signed</span><strong>{signed}</strong><small>completed approvals</small></article><article><span>Open invoices</span><strong>{unpaid}</strong><small>awaiting payment</small></article><article><span>Project</span><strong className="client-project-name">{profile.project||'In progress'}</strong><small>{profile.company||'ASHES client'}</small></article></section>
   <section className="client-grid"><div className="client-panel" id="documents"><div className="client-panel-head"><div><span>SHARED FILES</span><h2>Documents from Ashes</h2></div></div>{docs.length===0?<div className="portal-empty">Nothing has been shared yet.</div>:<div className="client-doc-list">{docs.map(d=><Fragment key={d._id}><div className="client-doc"><div className="client-doc-icon">A</div><div><strong>{d.title}</strong><span>{TYPE_LABELS[d.type]||d.type} · {new Date(d.createdAt).toLocaleDateString('en-GB')}</span></div><div className="client-doc-actions"><span className={`portal-badge ${d.status}`}>{d.status}</span><a className="pill-btn tiny" href={`/api/documents/${d._id}/download`} target="_blank" rel="noreferrer">Open</a>{d.type==='contract'&&!d.signedAt&&<button className="pill-btn tiny solid" onClick={()=>{setSigningDoc(d._id);setSignName(user?.name||'')}}>Sign</button>}</div></div>{signingDoc===d._id&&<div className="client-sign"><span>Type your full name to approve this agreement.</span><input value={signName} onChange={e=>setSignName(e.target.value)} placeholder="Full name"/><button className="pill-btn tiny solid" disabled={signing} onClick={()=>submitSignature(d._id)}>{signing?'Signing…':'Confirm signature'}</button><button className="pill-btn tiny" onClick={()=>setSigningDoc(null)}>Cancel</button></div>}</Fragment>)}</div>}</div>
    <div className="client-panel" id="profile"><div className="client-panel-head"><div><span>YOUR DETAILS</span><h2>Contact profile</h2></div></div>{saved&&<div className="portal-success">Saved.</div>}<form onSubmit={saveProfile}><div className="portal-field"><label>Gmail for meetings</label><input type="email" value={profile.googleEmail||''} onChange={e=>setProfile({...profile,googleEmail:e.target.value})} placeholder="you@gmail.com"/></div><div className="portal-field"><label>Phone</label><input value={profile.phone||''} onChange={e=>setProfile({...profile,phone:e.target.value})}/></div><div className="portal-grid-2"><div className="portal-field"><label>Age</label><input type="number" value={profile.age||''} onChange={e=>setProfile({...profile,age:Number(e.target.value)})}/></div><div className="portal-field"><label>Gender</label><select value={profile.gender||''} onChange={e=>setProfile({...profile,gender:e.target.value})}><option value="">Prefer not to say</option><option>Male</option><option>Female</option><option>Other</option></select></div></div><button className="pill-btn solid" disabled={saving}>{saving?'Saving…':'Save details'}</button></form></div>
   </section>
   <section id="profile"><AccountSettings profile={{name:profile.name,email:profile.email}} onUpdated={p=>setProfile({...profile,...p})}/></section>
   <section className="client-panel client-feedback" id="feedback"><div className="client-panel-head"><div><span>EXPERIENCE</span><h2>{myReview?'Your review':'How are we doing?'}</h2></div></div>{reviewSaved&&<div className="portal-success">Thanks — your review is live.</div>}<div className="client-stars">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>setReviewRating(n)} onMouseEnter={()=>setHoverStar(n)} onMouseLeave={()=>setHoverStar(0)} className={n<=(hoverStar||reviewRating)?'on':''}>★</button>)}</div><textarea className="client-review-input" value={reviewComment} onChange={e=>setReviewComment(e.target.value)} placeholder="Tell us about your experience…"/><button className="pill-btn solid" disabled={submittingReview||!reviewRating} onClick={submitReview}>{submittingReview?'Saving…':myReview?'Update review':'Submit review'}</button></section>
  </main>
 </div>
}
