import { ArrowUpRight, Bot, Box, BrainCircuit, Car, ChefHat, Flame, IceCreamBowl, MessageCircle, MessagesSquare, QrCode, ShieldCheck, ShoppingBag, Sparkles, UtensilsCrossed } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import Nav from '../components/Nav';
import Footer from '../components/Footer';
import { useSEO } from '../useSEO';

type Project = { name:string; category:string; copy:string; url:string; accent:string; icon:LucideIcon; featured?:boolean };
const projects: Project[] = [
  { name:'Porsche 911 Luxury', category:'3D AUTOMOTIVE EXPERIENCE', copy:'A cinematic, interactive luxury-car experience built around motion, detail and high-end digital storytelling.', url:'https://porsche-911-luxury.vercel.app', accent:'#ff5d4d', icon:Car, featured:true },
  { name:'Lizard Anatomy 3D', category:'INTERACTIVE EDUCATION', copy:'A scroll-driven digital dissection that reveals skin, flesh, muscles, organs and bone layer by layer.', url:'https://lizard-anatomy-3d.vercel.app', accent:'#baff47', icon:Box, featured:true },
  { name:'Ashes AI', category:'AI + 3D COMMERCE', copy:'Image-to-3D product generation, interactive viewing and tools designed for modern ecommerce workflows.', url:'https://ashes-ai.vercel.app', accent:'#ff54c8', icon:BrainCircuit, featured:true },
  { name:'RoboLab Simulator', category:'AI ROBOTICS SIMULATOR', copy:'A real-time browser robotics lab with 2D circuit wiring, 3D robot physics, live sensors, Arduino-style firmware and Gemini AI that can build, diagnose and run the simulator.', url:'https://robotsimulation.vercel.app', accent:'#42d7ff', icon:Bot, featured:true },
  { name:'Ashes Connect', category:'OMNICHANNEL COMMUNICATIONS', copy:'One customer workspace for calls, SMS, WhatsApp, social conversations, customer history and business communication.', url:'https://ashes-connect-app.vercel.app', accent:'#66ebf2', icon:MessagesSquare, featured:true },
  { name:'SayIt', category:'AI COMMUNICATION PRODUCT', copy:'An AI reply assistant that turns messages or screenshots into polished replies for WhatsApp, email, clients, support and everyday conversations.', url:'https://aireply-dusky.vercel.app', accent:'#9c7cff', icon:MessageCircle, featured:true },
  { name:'TrendDrop', category:'AI TREND INTELLIGENCE', copy:'A daily creator tool that finds rising topics by region, niche and platform, then turns them into a ready-to-film video idea with hook, structure, caption and hashtags.', url:'https://trenddrop-delta.vercel.app/', accent:'#ff3d8a', icon:Flame, featured:true },
  { name:'CuteQR Commerce', category:'ECOMMERCE AUTOMATION', copy:'A commerce tool connecting product data, QR experiences and multi-channel selling workflows.', url:'https://cuteqr-weld.vercel.app', accent:'#55d9ff', icon:QrCode, featured:true },
  { name:'HireGuard', category:'SERVICE MARKETPLACE', copy:'A polished multi-page security marketplace for discovering guards, comparing services and making enquiries.', url:'https://hire-a-guard-umc7.vercel.app', accent:'#68e0b7', icon:ShieldCheck },
  { name:'MFZ Food Experience', category:'3D RESTAURANT WEBSITE', copy:'A playful, motion-led restaurant concept with bold product presentation and immersive branded interactions.', url:'https://webiste-demo-eight.vercel.app', accent:'#ffb25c', icon:UtensilsCrossed },
  { name:'Ottimo Restaurant', category:'RESTAURANT CONCEPT', copy:'A refined restaurant interface exploring editorial layouts, tactile motion and mobile-first menu discovery.', url:'https://ai-website-making.vercel.app', accent:'#f1d18a', icon:ChefHat },
  { name:'AM PM Cafe', category:'3D FOOD EXPERIENCE', copy:'A modern cafe landing experience with dimensional food presentation, interaction and bold visual direction.', url:'https://am-pm-restaurent-pi.vercel.app', accent:'#fb8b58', icon:UtensilsCrossed },
  { name:'Maqbool Ice Cream', category:'PRODUCT LANDING PAGE', copy:'A colorful digital storefront concept focused on product personality, flavor and strong visual merchandising.', url:'https://maqbool-icecream.vercel.app', accent:'#7edbff', icon:IceCreamBowl },
  { name:'Piyali Restaurant', category:'RESTAURANT WEBSITE', copy:'A premium hospitality concept combining atmospheric layouts, menu discovery and an elegant booking journey.', url:'https://piyali-website.vercel.app', accent:'#caa46a', icon:ChefHat },
  { name:'Bell Cliff', category:'BRAND EXPERIENCE', copy:'A design-led digital experience built to present a distinctive brand with clarity, polish and responsive motion.', url:'https://bell-cliff-day07.vercel.app', accent:'#ad77ff', icon:Sparkles },
  { name:'Ecommerce Store', category:'FULL-STACK COMMERCE', copy:'A complete ecommerce build demonstrating product browsing, customer accounts, cart flows and store interactions.', url:'https://e-commerce-website-orcin-one.vercel.app', accent:'#ff7c9e', icon:ShoppingBag },
];
export default function WorkPage(){
 useSEO({title:'Ashes Portfolio — AI Products, Robotics, 3D Websites, Ecommerce & Digital Tools',description:'Explore live products and digital experiences built by Ashes, including RoboLab Simulator, Ashes Connect, TrendDrop, SayIt, Ashes AI, CuteQR, interactive 3D websites, ecommerce systems and web applications.',path:'/work'});
 return <><Nav/><main className="catalog-page"><header className="catalog-hero"><p className="catalog-kicker">03 / LIVE PROJECT CATALOG</p><h1>EVERY BUILD.<br/><span>ONE PLACE.</span></h1><div className="catalog-intro"><p>Explore websites, AI products, robotics simulations, 3D experiences and platforms designed and developed by Ashes.</p><strong><span>{projects.length}</span> LIVE BUILDS</strong></div></header><section className="catalog-grid" aria-label="Ashes project portfolio">{projects.map((project,index)=>{const Icon=project.icon;return <a className={`catalog-card${project.featured?' catalog-featured':''}`} href={project.url} target="_blank" rel="noreferrer" key={project.name} style={{'--project-accent':project.accent} as React.CSSProperties} aria-label={`Open ${project.name} live website`}><div className="catalog-card-top"><span>{String(index+1).padStart(2,'0')}</span><span className="catalog-live"><i/> LIVE</span></div><div className="catalog-icon"><Icon/></div><div className="catalog-copy"><small>{project.category}</small><h2>{project.name}</h2><p>{project.copy}</p></div><div className="catalog-open">OPEN PROJECT <ArrowUpRight/></div></a>})}</section><section className="catalog-cta"><p>LIKE WHAT YOU SEE?</p><h2>LET'S BUILD YOURS NEXT.</h2><a href="/contact">START A PROJECT <ArrowUpRight/></a></section></main><Footer/></>;
}
