import { ArrowDownRight, ArrowUpRight, Box, Braces, BrainCircuit, Camera, Crosshair, Scale, Sparkles, Smartphone } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import Nav from './components/Nav';

const powers=[
  {number:'01',title:'AI\nSYSTEMS',copy:'Intelligent systems that learn, reason and adapt.',icon:BrainCircuit,accent:'#55d9ff',mode:'ai'},
  {number:'02',title:'WEB\nEXPERIENCES',copy:'Fast, beautiful platforms that convert and scale.',icon:Braces,accent:'#ad77ff',mode:'web'},
  {number:'03',title:'MOBILE\nAPPS',copy:'Native-feeling products people actually love.',icon:Smartphone,accent:'#ffb25c',mode:'mobile'},
  {number:'04',title:'IMMERSIVE\n3D',copy:'Cinematic experiences that move people and brands.',icon:Box,accent:'#ff54c8',mode:'vr'}
];

function Reveal({children,className=''}:{children:React.ReactNode,className?:string}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const el=ref.current;if(!el)return;const io=new IntersectionObserver(([entry])=>{if(entry.isIntersecting)el.classList.add('shown')},{threshold:.12});io.observe(el);return()=>io.disconnect()},[]);return <div ref={ref} className={`reveal ${className}`}>{children}</div>}
function Phoenix({className='',variant='plain',priority=false}:{className?:string,variant?:string,priority?:boolean}){return <div className={`phoenix ${className} phoenix-${variant}`}><img src={variant==='vr'?'/ashes-phoenix-vr.webp':'/ashes-phoenix-hero.webp'} alt={variant==='vr'?'Ashes phoenix wearing a neon VR visor':'Ashes phoenix'} draggable={false} loading={priority?'eager':'lazy'} decoding="async" fetchPriority={priority?'high':'auto'}/></div>}
function PowerPhoenix({mode}:{mode:string}){return <img className="power-phoenix" src={`/powers/${mode}.webp`} alt={`${mode} phoenix`} loading="lazy" decoding="async"/>}
type TiltElement=HTMLElement&{tiltFrame?:number;tiltX?:number;tiltY?:number};
function tiltCard(event:React.PointerEvent<HTMLElement>){const card=event.currentTarget as TiltElement,rect=card.getBoundingClientRect();card.tiltX=(event.clientX-rect.left)/rect.width;card.tiltY=(event.clientY-rect.top)/rect.height;if(card.tiltFrame)return;card.tiltFrame=requestAnimationFrame(()=>{const x=card.tiltX??.5,y=card.tiltY??.5;card.style.setProperty('--rx',`${(0.5-y)*9}deg`);card.style.setProperty('--ry',`${(x-0.5)*11}deg`);card.style.setProperty('--gx',`${x*100}%`);card.style.setProperty('--gy',`${y*100}%`);card.tiltFrame=undefined})}
function resetCard(event:React.PointerEvent<HTMLElement>){const card=event.currentTarget as TiltElement;if(card.tiltFrame)cancelAnimationFrame(card.tiltFrame);card.tiltFrame=undefined;card.style.setProperty('--rx','0deg');card.style.setProperty('--ry','0deg');card.style.setProperty('--gx','50%');card.style.setProperty('--gy','50%')}
function SignalNetwork(){const canvasRef=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const context=canvas.getContext('2d',{alpha:true});if(!context)return;const colors=['#66ebf2','#ff62c7','#d8ff62','#ff875c','#ad77ff'];let width=0,height=0,frame=0,last=0,visible=true;const pointer={x:-9999,y:-9999};type Node={x:number,y:number,px:number,py:number,vx:number,vy:number,r:number,color:string,life:number,hot:boolean,curl:number,burst:boolean};let nodes:Node[]=[];
  const reset=(node?:Node)=>{const zone=Math.floor(Math.random()*4);let x:number,y:number,angle:number;if(zone===0){x=width*(.2+Math.random()*.31);y=height*(.17+Math.random()*.31);angle=Math.PI+(-.42+Math.random()*.84)}else if(zone===1){x=width*(.57+Math.random()*.25);y=height*(.22+Math.random()*.3);angle=-.42+Math.random()*.84}else if(zone===2){x=width*(.27+Math.random()*.3);y=height*(.56+Math.random()*.22);angle=Math.PI/2+(-.55+Math.random()*1.1)}else{x=width*(.46+Math.random()*.2);y=height*(.34+Math.random()*.25);angle=-.7+Math.random()*1.4}const speed=.78+Math.random()*1.2;const next={x,y,px:x,py:y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,r:1+Math.random()*2.15,color:colors[Math.floor(Math.random()*colors.length)],life:.74+Math.random()*.26,hot:false,curl:(Math.random()-.5)*.018,burst:false};if(node)Object.assign(node,next);else return next};
  const resize=()=>{const rect=canvas.getBoundingClientRect();width=rect.width;height=rect.height;canvas.width=Math.round(width);canvas.height=Math.round(height);context.setTransform(1,0,0,1,0,0);const permanent=nodes.filter(node=>!node.burst),target=width<700?18:40;nodes=[...permanent.slice(0,target),...Array.from({length:Math.max(0,target-permanent.length)},()=>reset() as Node),...nodes.filter(node=>node.burst)]};resize();const observer=new ResizeObserver(resize);observer.observe(canvas);const visibilityChange=()=>{visible=!document.hidden;if(visible&&!frame)frame=requestAnimationFrame(draw)};document.addEventListener('visibilitychange',visibilityChange);
  const move=(event:PointerEvent)=>{const rect=canvas.getBoundingClientRect();pointer.x=event.clientX-rect.left;pointer.y=event.clientY-rect.top};const leave=()=>{pointer.x=-9999;pointer.y=-9999};const ignite=(event:PointerEvent)=>{const rect=canvas.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)return;const x=event.clientX-rect.left,y=event.clientY-rect.top,count=width<700?7:10;for(let i=0;i<count;i++){const angle=Math.PI*2*i/count+(Math.random()-.5)*.35,speed=1.1+Math.random()*2.1;nodes.push({x,y,px:x,py:y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,r:1.4+Math.random()*2.2,color:colors[i%colors.length],life:.58+Math.random()*.18,hot:true,curl:(Math.random()-.5)*.024,burst:true})}const burstCap=width<700?16:24;const bursts=nodes.filter(node=>node.burst);if(bursts.length>burstCap){const remove=new Set(bursts.slice(0,bursts.length-burstCap));nodes=nodes.filter(node=>!remove.has(node))}};window.addEventListener('pointermove',move,{passive:true});window.addEventListener('pointerleave',leave);window.addEventListener('pointerdown',ignite,{passive:true});
  function draw(time:number){if(!visible){frame=0;return}if(time-last<16){frame=requestAnimationFrame(draw);return}last=time;context.clearRect(0,0,width,height);for(const node of nodes){node.px=node.x;node.py=node.y;const oldVx=node.vx;node.vx-=node.vy*node.curl;node.vy+=oldVx*node.curl;node.x+=node.vx;node.y+=node.vy;node.life-=node.burst?.014:.003;const dx=node.x-pointer.x,dy=node.y-pointer.y;node.hot=node.burst||dx*dx+dy*dy<7200;if(!node.burst&&(node.x< -40||node.x>width+40||node.y< -40||node.y>height+40||node.life<=0))reset(node)}nodes=nodes.filter(node=>!node.burst||node.life>0);
    const reach=width<700?76:108,reachSq=reach*reach;context.globalCompositeOperation='lighter';for(let i=0;i<nodes.length;i++){const a=nodes[i];for(let j=i+1;j<Math.min(nodes.length,i+7);j++){const b=nodes[j],dx=a.x-b.x,dy=a.y-b.y,distanceSq=dx*dx+dy*dy;if(distanceSq<reachSq){const strength=1-Math.sqrt(distanceSq)/reach,hot=a.hot||b.hot;context.beginPath();context.moveTo(a.x,a.y);context.lineTo(b.x,b.y);context.strokeStyle=hot?`rgba(235,252,255,${strength*.75})`:`rgba(130,220,235,${strength*.2})`;context.lineWidth=hot?1.25:.55;context.stroke()}}}
    for(const node of nodes){const energy=Math.min(1,node.life*1.8);context.beginPath();context.moveTo(node.px,node.py);context.lineTo(node.x-node.vx*4,node.y-node.vy*4);context.strokeStyle=node.color;context.globalAlpha=node.hot?.78:energy*.34;context.lineWidth=node.hot?1.8:Math.max(.5,node.r*.48);context.stroke();if(node.hot){context.beginPath();context.arc(node.x,node.y,node.r*3.2,0,Math.PI*2);context.fillStyle=node.color;context.globalAlpha=.16*energy;context.fill()}context.beginPath();context.arc(node.x,node.y,node.hot?node.r*1.65:node.r,0,Math.PI*2);context.fillStyle=node.hot?'#fff':node.color;context.globalAlpha=node.hot?energy:energy*.92;context.fill()}context.globalCompositeOperation='source-over';context.globalAlpha=1;frame=requestAnimationFrame(draw)}
  if(!matchMedia('(prefers-reduced-motion: reduce)').matches)frame=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(frame);observer.disconnect();document.removeEventListener('visibilitychange',visibilityChange);window.removeEventListener('pointermove',move);window.removeEventListener('pointerleave',leave);window.removeEventListener('pointerdown',ignite)}},[]);return <canvas ref={canvasRef} className="signal-network" aria-hidden="true"/>}

export default function App(){const [power,setPower]=useState(0);return <>
  <div className="grain"/><SignalNetwork/><Nav/>
  <main>
    <section id="top" className="hero"><div className="radar radar-a"/><div className="radar radar-b"/><div className="energy-aura" aria-hidden="true"/><Phoenix className="hero-phoenix" variant="vr" priority/><div className="hero-energy"/>
      <div className="hero-copy hero-left"><p className="hero-index">01 / DESIGN-LED SOFTWARE</p><h1>WE<br/>BUILD</h1><p className="hero-intro">Digital products engineered<br/>to move people and business.</p><a href="#capabilities">EXPLORE ASHES <ArrowDownRight/></a></div>
      <div className="hero-copy hero-right"><p className="hero-index">ISLAMABAD · EVERYWHERE</p><h1>WHAT<br/>RISES<br/>NEXT.</h1></div>
      <div className="orbit-label orbit-ai"><i/>AI</div><div className="orbit-label orbit-web"><i/>WEB</div><div className="orbit-label orbit-apps"><i/>APPS</div><div className="orbit-label orbit-3d"><i/>3D</div>
      <a className="scroll-cue" href="#capabilities">SCROLL TO EXPLORE <ArrowDownRight/></a>
    </section>

    <section id="capabilities" className="capabilities"><Reveal><p className="kicker">02 / CAPABILITIES</p><h2>ONE STUDIO.<br/><span>FOUR WAYS TO BUILD.</span></h2><p className="section-lede">Strategy, design and engineering—connected from first thought to final release.</p><p className="hint"><span>◉</span> HOVER TO ENTER EACH WORLD</p></Reveal>
      <div className="power-grid">{powers.map((p,i)=>{const Icon=p.icon;return <article key={p.mode} className={`power-card power-${p.mode} ${power===i?'active':''}`} style={{'--accent':p.accent} as React.CSSProperties} onMouseEnter={()=>setPower(i)} onPointerMove={tiltCard} onPointerLeave={resetCard}>
        <div className="card-glare"/><div className="cyber-lines"><i/><i/><i/><i/></div><div className="card-particles"><i/><i/><i/><i/><i/><i/></div><div className="corner-elements"><i/><i/><i/><i/></div><div className="scan-line"/>
        <span className="power-no">{p.number}</span><Icon className="power-icon"/><h3>{p.title.split('\n').map(x=><span key={x}>{x}</span>)}</h3><p>{p.copy}</p><div className="power-scene"><PowerPhoenix mode={p.mode}/></div><ArrowUpRight className="card-arrow"/></article>})}</div>
    </section>

    <section id="work" className="work"><Reveal><p className="kicker">03 / SELECTED WORK</p><div className="title-row"><h2>BUILT TO WORK.<br/><span>MADE TO BE REMEMBERED.</span></h2><p>THREE PRODUCTS · ONE STANDARD</p></div></Reveal><div className="work-stage"><div className="work-cards">
      <article className="work-project work-ashes"><div className="work-copy"><small>01 / IMAGE → 3D</small><h3>ASHES AI</h3><p>One image in. A product you can spin, explore and sell in 3D.</p></div><div className="project-scene"><img src="/ashes-phoenix-hero.webp" alt="Red Ashes phoenix presenting a 3D product"/><div className="scene-prop prop-3d"><Box/><span>3D</span></div><i className="scene-orbit orbit-one"/><i className="scene-orbit orbit-two"/></div><b>EXPLORE 3D</b></article>
      <article className="work-project work-nazar"><div className="work-copy"><small>02 / VISION AI</small><h3>NAZAR AI</h3><p>A funky camera-powered watcher for activity, safety and the physical world.</p></div><div className="project-scene"><img src="/ashes-phoenix-hero.webp" alt="Ashes phoenix with a camera for Nazar AI"/><div className="scene-prop prop-camera"><Camera/><span>REC</span></div><i className="camera-bracket bracket-a"/><i className="camera-bracket bracket-b"/><div className="camera-label">TRACKING · LIVE</div></div><b>SEE NAZAR</b></article>
      <article className="work-project work-law"><div className="work-copy"><small>03 / LEGAL AI</small><h3>WAKULAW</h3><p>Pakistani legal intelligence with research, reasoning and case support.</p></div><div className="project-scene"><img src="/ashes-phoenix-hero.webp" alt="Ashes phoenix holding the scales of justice for WakuLAW"/><div className="scene-prop prop-scales"><Scale/><span>LAW</span></div><div className="law-line line-a"/><div className="law-line line-b"/></div><b>ASK THE LAW</b></article>
    </div></div></section>

    <section className="philosophy philosophy-redesign"><div className="philosophy-glow philosophy-glow-a"/><div className="philosophy-glow philosophy-glow-b"/><Reveal className="philosophy-head"><p className="kicker">04 / OUR PHILOSOPHY</p><h2>SERIOUS ENGINEERING.<br/><span>UNREASONABLY GOOD DESIGN.</span></h2><p>Every Ashes product has to earn both halves: it must work beautifully and look impossible to ignore.</p></Reveal><div className="philosophy-world"><div className="philosophy-phoenix-wrap"><span className="philosophy-orbit orbit-a"/><span className="philosophy-orbit orbit-b"/><div className="philosophy-core"><div className="philosophy-core-badge">ASHES<br/><small>BUILD STANDARD</small></div></div></div><div className="principle-grid"><article className="principle-card principle-think"><div className="principle-icon"><Crosshair/></div><span>01 / THINK</span><h3>THINK<br/>SHARP.</h3><p>Question the obvious. Find the cleanest path. Solve the real problem before touching the pixels.</p><b>CLARITY OVER NOISE</b></article><article className="principle-card principle-build"><div className="principle-icon"><Box/></div><span>02 / BUILD</span><h3>BUILD<br/>SOLID.</h3><p>Fast is good. Fragile is not. We care about systems that keep working after the launch-day glow fades.</p><b>CRAFT OVER SHORTCUTS</b></article><article className="principle-card principle-iconic"><div className="principle-icon"><Sparkles/></div><span>03 / DESIGN</span><h3>MAKE IT<br/>ICONIC.</h3><p>The tiny details matter. Motion, rhythm, spacing and personality should make the product feel unmistakably alive.</p><b>MEMORABLE BY DESIGN</b></article></div></div><div className="philosophy-manifesto"><span>NO EMPTY HYPE.</span><i/> <span>NO BORING SOFTWARE.</span><i/> <span>NO THROWAWAY DETAILS.</span></div></section>

    <section id="process" className="process"><Reveal><p className="kicker">OUR PROCESS</p><h2>FROM FIRST PRINCIPLE<br/>TO FINAL PIXEL.</h2></Reveal><div className="process-world"><div className="process-core"/><div className="process-grid">{['VIBE CHECK','MAKE IT\nMAKE SENSE','BUILD\nTHE THING','SHIP &\nEVOLVE'].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x.split('\n').map(v=><em key={v}>{v}</em>)}</b><small>{['Discover','Design','Engineer','Improve'][i]}</small></div>)}</div></div></section>

    <section id="studio" className="about"><Reveal><p className="kicker">ABOUT ASHES</p><h2>ASHES IS A DESIGN-LED<br/>SOFTWARE HOUSE FOR<br/>BRANDS THAT REFUSE<br/>TO BE BORING.</h2><p className="about-lede">Ashes is a design-led software house based in Islamabad, Pakistan, building websites, web applications, and AI-powered products for startups and growing brands. We specialize in custom web design, full-stack development, product engineering, and AI integration — turning ambitious ideas into fast, polished, production-ready software.</p><div className="about-tags"><span>Web Design</span><span>Full-Stack Development</span><span>Product Engineering</span><span>AI Integration</span><span>Islamabad, Pakistan</span></div></Reveal></section>

    <section className="cta"><div className="cta-energy" aria-hidden="true"/><div><p className="kicker">START SOMETHING UNIGNORABLE.</p><h2>GOT A WILD IDEA?<br/>GOOD. WE LIKE THOSE.</h2><a href="mailto:hello@ashes.studio">LET'S BUILD IT <ArrowUpRight/></a></div></section>
  </main><footer><div className="footer-brand"><span>ASHES</span><p>Software that refuses<br/>to be forgettable.</p></div><div className="footer-contact"><span>START SOMETHING</span><a href="mailto:hello@ashes.studio">hello@ashes.studio ↗</a></div><nav><a href="#">INSTAGRAM</a><a href="#">LINKEDIN</a><a href="#">GITHUB</a><a href="#top">BACK TO TOP ↑</a></nav><small>© 2026 ASHES · ISLAMABAD / EVERYWHERE</small></footer>
  </>}
