import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import ProcessScrollFlight from './ProcessScrollFlight';
import LowerPageSocials from './LowerPageSocials';
import './index.css';
import './card-image-size.css';
import './performance.css';
import './selected-work.css';
import './philosophy.css';
import './process-section.css';
import './final-sections.css';
import './about-section.css';
createRoot(document.getElementById('root')!).render(<StrictMode><App/><ProcessScrollFlight/><LowerPageSocials/></StrictMode>);
